# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Callable, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'ProviderCertmanagerArgs',
]

@pulumi.input_type
class ProviderCertmanagerArgs:
    def __init__(__self__, *,
                 mtls_cert_pem: pulumi.Input[str],
                 mtls_key_pem: pulumi.Input[str]):
        ProviderCertmanagerArgs._configure(
            lambda key, value: pulumi.set(__self__, key, value),
            mtls_cert_pem=mtls_cert_pem,
            mtls_key_pem=mtls_key_pem,
        )
    @staticmethod
    def _configure(
             _setter: Callable[[Any, Any], None],
             opts: Optional[pulumi.ResourceOptions]=None,
             **kwargs):
        if 'mtls_cert_pem' in kwargs:
            mtls_cert_pem = kwargs['mtls_cert_pem']
        if 'mtls_cert_pem' not in locals():
            raise TypeError("Missing required property 'mtls_cert_pem'")
        if 'mtls_key_pem' in kwargs:
            mtls_key_pem = kwargs['mtls_key_pem']
        if 'mtls_key_pem' not in locals():
            raise TypeError("Missing required property 'mtls_key_pem'")

        _setter("mtls_cert_pem", mtls_cert_pem)
        _setter("mtls_key_pem", mtls_key_pem)

    @property
    @pulumi.getter
    def mtls_cert_pem(self) -> pulumi.Input[str]:
        return pulumi.get(self, "mtls_cert_pem")

    @mtls_cert_pem.setter
    def mtls_cert_pem(self, value: pulumi.Input[str]):
        pulumi.set(self, "mtls_cert_pem", value)

    @property
    @pulumi.getter
    def mtls_key_pem(self) -> pulumi.Input[str]:
        return pulumi.get(self, "mtls_key_pem")

    @mtls_key_pem.setter
    def mtls_key_pem(self, value: pulumi.Input[str]):
        pulumi.set(self, "mtls_key_pem", value)


